### ISSUE TITLE
Id change in layer page causes blank screen

### ISSUE THREAD

**Issue by PetersonGIS** [go-spatial/fresco#40] opened 2018-04-29 16:07 UTC
Changing an id causes fresco to disappear, leaving just the map background color. Clicking the browser's back arrow, then refreshing the page will make fresco reappear. (The id change _is_ saved.)

**Comment by ARolek** [comment] 2018-05-23 22:17
This one is frustrating. Not quite sure what the solution is though.

**Comment by ARolek** [comment] 2018-05-24 20:30
This is a dupe of #6. Closing

**Closed by ARolek** 2018-05-24 20:30 UTC
